{
  "sksl": {
    "entrypoint": "waterShaderV2_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float uTime;\nuniform vec2 uSize;\nuniform float distortionStrength;\nuniform vec2 scroll;\nuniform vec4 toneColor;\nuniform vec4 lightColor;\nuniform float opacity;\nuniform vec2 lightRange;\nuniform shader uTexture;\nuniform half2 uTexture_size;\nuniform shader uNoise;\nuniform half2 uNoise_size;\nuniform shader uSecondNoise;\nuniform half2 uSecondNoise_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 scroll2 = scroll * (-1.0);\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec2 scrolledUV = fract(uv + (scroll * uTime));\n    vec2 scrolledUV2 = fract(uv + (scroll2 * uTime));\n    float depth = uNoise.eval(uNoise_size * ( scrolledUV)).x * uSecondNoise.eval(uSecondNoise_size * ( scrolledUV2)).x;\n    vec4 screen_col = uTexture.eval(uTexture_size * ( uv + (vec2(depth) * distortionStrength)));\n    vec4 topLight = lightColor * smoothstep(lightRange.x, lightRange.y, depth);\n    fragColor = mix(screen_col + topLight, toneColor, vec4(opacity));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 2,
        "name": "uTexture",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "distortionStrength",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 4,
        "name": "uNoise",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 5,
        "name": "uSecondNoise",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 6,
        "name": "scroll",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 7,
        "name": "toneColor",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 8,
        "name": "lightColor",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 9,
        "name": "opacity",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 10,
        "name": "lightRange",
        "rows": 2,
        "type": 10
      }
    ]
  }
}