{
  "sksl": {
    "entrypoint": "waterShader_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float uTime;\nuniform vec2 uSize;\nuniform vec2 scroll;\nuniform vec4 toneColor;\nuniform shader uTexture;\nuniform half2 uTexture_size;\nuniform shader uNoise;\nuniform half2 uNoise_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    float distortion_strength = 0.00999999977648258209228515625;\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec2 scrolledUV = fract(uv + (scroll * uTime));\n    vec4 noise_col = uNoise.eval(uNoise_size * ( scrolledUV));\n    vec2 distorted_uv = uv + (((noise_col.xy * 2.0) - vec2(1.0)) * distortion_strength);\n    vec4 screen_col = uTexture.eval(uTexture_size * ( distorted_uv));\n    fragColor = mix(screen_col, toneColor, vec4(0.60000002384185791015625));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 2,
        "name": "uTexture",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 3,
        "name": "uNoise",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "scroll",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "toneColor",
        "rows": 4,
        "type": 10
      }
    ]
  }
}